name: main
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [pypi_release]

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.event_name, 'repository_dispatch') }}
        run: sleep 30

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: download uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - run: uv pip install --system -r requirements-dev.txt

      - name: set git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - run: python mirror.py

      - run: |
          git push origin HEAD:refs/heads/main
          git push origin HEAD:refs/heads/main --tags
